### ISSUE TITLE
Does not work on Android projects

### ISSUE THREAD

**Issue by autonomousapps** [MarkusAmshove/Kluent#66]
Use:
```
import org.amshove.kluent.mock
val m: AppData = mock(AppData::class)
```
Error:
```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/amshove/kluent/MockingKt;
at com.myproject.tests.Test.testSomething(Test.kt:91)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:270)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at com.jakewharton.u2020.U2020TestRunner.onStart(U2020TestRunner.java:22)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.amshove.kluent.MockingKt" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.myproject.test-2/base.apk", zip file "/data/app/com.myproject-2/base.apk"],nativeLibraryDirectories=[/data/app/com.myproject.test-2/lib/x86, /data/app/com.myproject-2/lib/x86, /data/app/com.myproject.test-2/base.apk!/lib/x86, /data/app/com.myproject-2/base.apk!/lib/x86, /system/lib, /vendor/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 34 more
```

**Comment by autonomousapps** [comment]
Note: I have a similar issue with the Mockito Kotlin project, and have filed a sibling issue there: https://github.com/nhaarman/mockito-kotlin/issues/200

**Comment by autonomousapps** [comment]
No ideas?

**Comment by MarkusAmshove** [comment]
I just looked through your linked mockito-kotlin issue.
If it works with mockito-kotlin Android, it might work if we also use the Android version for our Android version. 
I'll write up how you could test it locally tomorrow so we can fix it :-)

**Comment by autonomousapps** [comment]
Yeah, actually, that'll probably address it, assuming those other guys are right. I just haven't had a chance to try it yet.

**Comment by MarkusAmshove** [comment]
Is the app you've tried it on at Github so I can try it out?
Or maybe a new minimal not working example :-)

**Comment by MarkusAmshove** [comment]
Any updates on this?

**Comment by lukaville** [comment]
@MarkusAmshove @autonomousapps 
It took few hours to find out that it fails because of incorrectly generated dex file:
`02-26 01:30:28.450 14028-14028/? E/dex2oat: Failed to open dex file from oat file. File: base.apk!classes3.dex Error: Failure to verify dex file 'base.apk!classes3.dex': Invalid field name: 'Verify no further interactions'`

Looks like there are problems with spaces in field names, so entire "classes3.dex" not loaded because of that and any access to classes from this dex file cause to ClassNotFound exception.

**Comment by MarkusAmshove** [comment]
@lukaville which version of Kluent are you using? There is an Android version without backticks, as of writing 1.35:

```
dependencies {
    // for Android:
    testImplementation 'org.amshove.kluent:kluent-android:{version}'
}
```

**Comment by autonomousapps** [comment]
Sorry I never got back to you! It was a very busy end-of-year for me and I'm finally coming up for air. I'm actually working on a greenfield project (yay), so it's much easier to experiment with things.

**Comment by MarkusAmshove** [comment]
good to hear 😄  if you encounter the same problems feel free to reopen!
